### ISSUE TITLE
D3 not installing with bower

### ISSUE THREAD

**Issue by JordanCollins** [colorfest/d3js#1]
Just an issue that I found running through your tutorials: the d3 folder was not installed as part of my bower_components. Each of the other components were successfully installed, except for d3.

**Comment by baderj** [comment]
Ran into the same issue. The ``bower.json`` is missing a D3 entry. Fix:
```
"dependencies": {    
   "d3": "^4.11.0"                                                          
   ...
```

Alternatively, you can also install it with npm. Add the D3 line to ``package.json``:

```
"devDependencies": {                                                          
    "d3": "~4.11.0",                                                            
    ....                        
```
You need to change the d3 path if you use npm to install d3.

**Comment by DadUndead** [comment]
I't won't work with 4.11.0 because of d3 x3 API changes. So it can be fixed with older d3 version. 
Changes in `bower.json`:
`
"devDependencies": {                                                          
    "d3": "^3.5.17",  
....
`
